image: gitpod/workspace-dotnet

ports:
  - port: 5001
    onOpen: ignore
  - port: 4200
    onOpen: open-preview
    
tasks:
  - command: |
      cd server/iterate.Ruhr-Server
      dotnet run --urls http://0.0.0.0:5001
  - init: |
      export NG_CLI_ANALYTICS=ci
      npm install -g @angular/cli
      export BACKEND_URL=$(gp url 5001 | sed 's/https:\/\///g')
      cd client
      envsubst < src/environments/environment.template.ts > src/environments/environment.ts
      npm install
    command: |
      export NG_CLI_ANALYTICS=ci
      npm start
